export const ROAMER_BUTTERFLY_WING_PAIR_COUNT = 9;

export const ROAMER_BUTTERFLY_WING_STRETCH_GAIN = 0.3;
export const ROAMER_BUTTERFLY_WING_THIN_GAIN = 0.15;
export const ROAMER_BUTTERFLY_WING_LENGTH = 0.8;
export const ROAMER_BUTTERFLY_WING_WIDTH = 0.35;

export const ROAMER_BUTTERFLY_BODY_LENGTH = 60;
export const ROAMER_BUTTERFLY_BODY_THICKNESS = 40;
export const ROAMER_BUTTERFLY_BODY_SCALE = 1;
export const ROAMER_BUTTERFLY_RENDER_BOUNDS_MARGIN = 10;
export const ROAMER_BUTTERFLY_HIT_RADIUS = 30;
export const ROAMER_BUTTERFLY_DECORATIVE_COUNT = 8;
