export const ROAMER_BUTTERFLY_WING_PAIR_COUNT = 9;

export const ROAMER_BUTTERFLY_WING_STRETCH_GAIN = 5.0;
export const ROAMER_BUTTERFLY_WING_THIN_GAIN = 1.0;
export const ROAMER_BUTTERFLY_WING_LENGTH_RATIO = 0.9;
export const ROAMER_BUTTERFLY_WING_WIDTH_RATIO = 0.8;

export const ROAMER_BUTTERFLY_BODY_LENGTH = 45;
export const ROAMER_BUTTERFLY_BODY_THICKNESS = 36;
export const ROAMER_BUTTERFLY_BODY_SCALE = 1;
export const ROAMER_BUTTERFLY_RENDER_BOUNDS_MARGIN = 10;
export const ROAMER_BUTTERFLY_HIT_RADIUS = 30;
export const ROAMER_BUTTERFLY_DECORATIVE_COUNT = 8;
