import type { RoamerConfig } from '../../core/roamerConfig';

export const ROAMER_BUTTERFLY_WING_PAIR_COUNT = 9;
export const ROAMER_BUTTERFLY_LEG_COUNT = 6;
export const ROAMER_BUTTERFLY_SITTING_FLOWER_COUNT = 12;

export const ROAMER_BUTTERFLY_WING_PAIR_PICK_BIAS = 20;
export const ROAMER_BUTTERFLY_SIT_TRANSITION_MS = 300;
export const ROAMER_BUTTERFLY_SIT_MOVE_RADIUS = 15;
export const ROAMER_BUTTERFLY_SIT_MOVE_SPEED = 10;
export const ROAMER_BUTTERFLY_SIT_MOVE_VERTICAL_SQUASH = 0.5;
export const ROAMER_BUTTERFLY_SIT_PAUSE_DURATION_MS = 4000;
export const ROAMER_BUTTERFLY_SIT_MOVE_TURN_SPEED = 1.0;
export const ROAMER_BUTTERFLY_SIT_BODY_SCALE = 0.9;
export const ROAMER_BUTTERFLY_SIT_DURATION_MIN_MS = 5000;
export const ROAMER_BUTTERFLY_SIT_DURATION_MAX_MS = 12000;
export const ROAMER_BUTTERFLY_WAIT_AT_TAKEN_FLOWER_PATIENCE_MS = 3000;
export const ROAMER_BUTTERFLY_LIFT_OFF_DURATION_MS = 500;
export const ROAMER_BUTTERFLY_FLIGHT_PICK_FLOWER_PROBABILITY = 0.2;
export const ROAMER_BUTTERFLY_SIT_LEG_FREQUENCY = 3;
export const ROAMER_BUTTERFLY_LEG_FREQUENCY = 10;
export const ROAMER_BUTTERFLY_LEG_BEND_AMOUNT = 0.3;
export const ROAMER_BUTTERFLY_LEG_VISIBILITY_FADE_IN_MS = 300;
export const ROAMER_BUTTERFLY_LEG_VISIBILITY_FADE_OUT_MS = 300;

export const ROAMER_BUTTERFLY_LEG_TRIPOD_OFFSETS: readonly number[] = [
  0,        // FL — Group A: (FL, MR, BL) move together
  Math.PI,  // FR — Group B: (FR, ML, BR) antiphase
  Math.PI,  // ML — Group B
  0,        // MR — Group A
  0,        // BL — Group A
  Math.PI,  // BR — Group B
];

export const ROAMER_BUTTERFLY_APPROACH_DISTANCE_THRESHOLD = 3;
export const ROAMER_BUTTERFLY_WING_FREQ_MIN = 7;
export const ROAMER_BUTTERFLY_WING_FREQ_MAX = 10;
export const ROAMER_BUTTERFLY_SIT_WING_FREQ_MIN = 1;
export const ROAMER_BUTTERFLY_SIT_WING_FREQ_MAX = 3;
export const ROAMER_BUTTERFLY_APPROACH_ORBIT_DURATION_MIN = 3.0;
export const ROAMER_BUTTERFLY_APPROACH_ORBIT_DURATION_MAX = 8.0;
export const ROAMER_BUTTERFLY_SIT_WING_PAUSE_DURATION_MIN_MS = 200;
export const ROAMER_BUTTERFLY_SIT_WING_PAUSE_DURATION_MAX_MS = 1000;

export const ROAMER_BUTTERFLY_NOISE_AMPLITUDE_MIN = 30;
export const ROAMER_BUTTERFLY_NOISE_AMPLITUDE_MAX = 220;
export const ROAMER_BUTTERFLY_NOISE_FREQ_MIN = 5;
export const ROAMER_BUTTERFLY_NOISE_FREQ_MAX = 20;

export const ROAMER_BUTTERFLY_DEFAULT_SPEED = 80;
export const ROAMER_BUTTERFLY_BOUNDARY_MARGIN = 50;
export const ROAMER_BUTTERFLY_SEPARATION_RADIUS = 60;
export const ROAMER_BUTTERFLY_SEPARATION_STEER = 5;
export const ROAMER_BUTTERFLY_BOUNDARY_TURN_OFFSET = 0.5;
export const ROAMER_BUTTERFLY_SWIM_ZONE_TOP_RATIO = 0.5;
export const ROAMER_BUTTERFLY_HIT_RADIUS = 30;

export const ROAMER_BUTTERFLY_BASE_SPEED_MIN = 40;
export const ROAMER_BUTTERFLY_BASE_SPEED_MAX = 240;
export const ROAMER_BUTTERFLY_CRUISE_DURATION_MIN = 1.5;
export const ROAMER_BUTTERFLY_CRUISE_DURATION_MAX = 5.0;
export const ROAMER_BUTTERFLY_CRUISE_DURATION_JITTER = 1.0;

export const ROAMER_BUTTERFLY_IDLE_DURATION_BASE = 1.2;
export const ROAMER_BUTTERFLY_IDLE_DURATION_JITTER = 0.6;

export const ROAMER_BUTTERFLY_ANGLE_LERP = 2.5;
export const ROAMER_BUTTERFLY_WANDER_LERP = 1.0;
export const ROAMER_BUTTERFLY_SPEED_LERP_FACTOR = 4.0;

export const ROAMER_BUTTERFLY_BOUNDARY_MARGIN_RATIO = 0.18;

export const ROAMER_BUTTERFLY_WANDER_DEVIATION_MIN = -Math.PI;
export const ROAMER_BUTTERFLY_WANDER_DEVIATION_MAX = Math.PI;

export const ROAMER_BUTTERFLY_IDLE_NOISE_AMPLITUDE = 70;
export const ROAMER_BUTTERFLY_IDLE_NOISE_FREQUENCY = 8;

export const ROAMER_BUTTERFLY_IDLE_DRIFT_SPEED = 6;
export const ROAMER_BUTTERFLY_SIM_FPS = 30;
export const ROAMER_BUTTERFLY_SIM_STEP_MS = 1000 / ROAMER_BUTTERFLY_SIM_FPS;

export const ROAMER_BUTTERFLY_LAND_AMPLITUDE_BOOST = 12;
export const ROAMER_BUTTERFLY_TAKEOFF_AMPLITUDE_BOOST = 8;
export const FLOWER_SWING_BOOST_DECAY_RATE = 2.5;

export const butterflyRoamerConfig: RoamerConfig = {
  baseSpeedMin: ROAMER_BUTTERFLY_BASE_SPEED_MIN,
  baseSpeedMax: ROAMER_BUTTERFLY_BASE_SPEED_MAX,
  cruiseDurationMin: ROAMER_BUTTERFLY_CRUISE_DURATION_MIN,
  cruiseDurationMax: ROAMER_BUTTERFLY_CRUISE_DURATION_MAX,
  cruiseDurationJitter: ROAMER_BUTTERFLY_CRUISE_DURATION_JITTER,
  idleDurationBase: ROAMER_BUTTERFLY_IDLE_DURATION_BASE,
  idleDurationJitter: ROAMER_BUTTERFLY_IDLE_DURATION_JITTER,
  angleLerp: ROAMER_BUTTERFLY_ANGLE_LERP,
  wanderLerp: ROAMER_BUTTERFLY_WANDER_LERP,
  speedLerpFactor: ROAMER_BUTTERFLY_SPEED_LERP_FACTOR,

  noiseAmplitudeMin: ROAMER_BUTTERFLY_NOISE_AMPLITUDE_MIN,
  noiseAmplitudeMax: ROAMER_BUTTERFLY_NOISE_AMPLITUDE_MAX,
  noiseFreqMin: ROAMER_BUTTERFLY_NOISE_FREQ_MIN,
  noiseFreqMax: ROAMER_BUTTERFLY_NOISE_FREQ_MAX,
  idleNoiseAmplitude: ROAMER_BUTTERFLY_IDLE_NOISE_AMPLITUDE,
  idleNoiseFrequency: ROAMER_BUTTERFLY_IDLE_NOISE_FREQUENCY,
  idleDriftSpeed: ROAMER_BUTTERFLY_IDLE_DRIFT_SPEED,

  boundaryTurnOffset: ROAMER_BUTTERFLY_BOUNDARY_TURN_OFFSET,
  boundaryMarginRatio: ROAMER_BUTTERFLY_BOUNDARY_MARGIN_RATIO,
  separationRadius: ROAMER_BUTTERFLY_SEPARATION_RADIUS,
  separationSteer: ROAMER_BUTTERFLY_SEPARATION_STEER,

  wingFreqMin: ROAMER_BUTTERFLY_WING_FREQ_MIN,
  wingFreqMax: ROAMER_BUTTERFLY_WING_FREQ_MAX,

  approachDistanceThreshold: ROAMER_BUTTERFLY_APPROACH_DISTANCE_THRESHOLD,
  approachOrbitDurationMin: ROAMER_BUTTERFLY_APPROACH_ORBIT_DURATION_MIN,
  approachOrbitDurationMax: ROAMER_BUTTERFLY_APPROACH_ORBIT_DURATION_MAX,
  flightPickFlowerProbability: ROAMER_BUTTERFLY_FLIGHT_PICK_FLOWER_PROBABILITY,
  sitTransitionMs: ROAMER_BUTTERFLY_SIT_TRANSITION_MS,
  sitMoveRadius: ROAMER_BUTTERFLY_SIT_MOVE_RADIUS,
  sitMoveSpeed: ROAMER_BUTTERFLY_SIT_MOVE_SPEED,
  sitMoveVerticalSquash: ROAMER_BUTTERFLY_SIT_MOVE_VERTICAL_SQUASH,
  sitPauseDurationMs: ROAMER_BUTTERFLY_SIT_PAUSE_DURATION_MS,
  sitMoveTurnSpeed: ROAMER_BUTTERFLY_SIT_MOVE_TURN_SPEED,
  sitBodyScale: ROAMER_BUTTERFLY_SIT_BODY_SCALE,
  sitDurationMinMs: ROAMER_BUTTERFLY_SIT_DURATION_MIN_MS,
  sitDurationMaxMs: ROAMER_BUTTERFLY_SIT_DURATION_MAX_MS,
  waitAtTakenFlowerPatienceMs: ROAMER_BUTTERFLY_WAIT_AT_TAKEN_FLOWER_PATIENCE_MS,
  liftOffDurationMs: ROAMER_BUTTERFLY_LIFT_OFF_DURATION_MS,
  sitWingFreqMin: ROAMER_BUTTERFLY_SIT_WING_FREQ_MIN,
  sitWingFreqMax: ROAMER_BUTTERFLY_SIT_WING_FREQ_MAX,
  sitWingPauseDurationMinMs: ROAMER_BUTTERFLY_SIT_WING_PAUSE_DURATION_MIN_MS,
  sitWingPauseDurationMaxMs: ROAMER_BUTTERFLY_SIT_WING_PAUSE_DURATION_MAX_MS,

  landAmplitudeBoost: ROAMER_BUTTERFLY_LAND_AMPLITUDE_BOOST,
  takeoffAmplitudeBoost: ROAMER_BUTTERFLY_TAKEOFF_AMPLITUDE_BOOST,
  flowerSwingBoostDecayRate: FLOWER_SWING_BOOST_DECAY_RATE,

  legFrequency: ROAMER_BUTTERFLY_LEG_FREQUENCY,
  legBendAmount: ROAMER_BUTTERFLY_LEG_BEND_AMOUNT,
  legVisibilityFadeInMs: ROAMER_BUTTERFLY_LEG_VISIBILITY_FADE_IN_MS,
  legVisibilityFadeOutMs: ROAMER_BUTTERFLY_LEG_VISIBILITY_FADE_OUT_MS,

  simFps: ROAMER_BUTTERFLY_SIM_FPS,
  simStepMs: ROAMER_BUTTERFLY_SIM_STEP_MS,
};
