export const ROAMER_BUTTERFLY_WING_PAIR_COUNT = 9;

export const ROAMER_BUTTERFLY_WING_STRETCH_GAIN = 5.0;
export const ROAMER_BUTTERFLY_WING_THIN_GAIN = 1.0;
export const ROAMER_BUTTERFLY_WING_LENGTH_RATIO = 0.9;
export const ROAMER_BUTTERFLY_WING_WIDTH_RATIO = 0.8;

export const ROAMER_BUTTERFLY_BODY_LENGTH = 45;
export const ROAMER_BUTTERFLY_BODY_THICKNESS = 36;
export const ROAMER_BUTTERFLY_BODY_SCALE = 1;
export const ROAMER_BUTTERFLY_RENDER_BOUNDS_MARGIN = 10;
export const ROAMER_BUTTERFLY_HIT_RADIUS = 30;
export const ROAMER_BUTTERFLY_DECORATIVE_COUNT = 4;

export const ROAMER_BUTTERFLY_SHADOW_OFFSET_SITTING_X = 3;
export const ROAMER_BUTTERFLY_SHADOW_OFFSET_SITTING_Y = 5;
export const ROAMER_BUTTERFLY_SHADOW_OFFSET_FLYING_X = 10;
export const ROAMER_BUTTERFLY_SHADOW_OFFSET_FLYING_Y = -50;
export const ROAMER_BUTTERFLY_SHADOW_SIZE_SITTING = 1.0;
export const ROAMER_BUTTERFLY_SHADOW_SIZE_FLYING = 1.3;
export const ROAMER_BUTTERFLY_SHADOW_OPACITY_SITTING = 0.5;
export const ROAMER_BUTTERFLY_SHADOW_OPACITY_FLYING = 0.2;
