export const ROAMER_BUBBLE_ESCAPE_ARRIVAL_THRESHOLD = 48;
export const ROAMER_BUBBLE_ESCAPE_ANGLE_LERP = 10.0;
export const ROAMER_BUBBLE_ESCAPE_SCREEN_MARGIN = 8;
export const ROAMER_BUBBLE_ESCAPE_SPEED_LERP_FACTOR = 8;
export const ROAMER_BUBBLE_ESCAPE_STATE_TIMER = 999;

/** Minimum hard-radius as a fraction of fish body inset inside the bubble. */
export const ROAMER_BUBBLE_HARD_RADIUS_MIN_BODY_RATIO = 0.25;
export const ROAMER_BUBBLE_CLAMP_EPSILON = 0.001;
export const ROAMER_BUBBLE_ESCAPE_BODY_MARGIN_RATIO = 0.5;
