export const FLOWER_GARDEN_OVERLAY_DARK = 'rgba(12, 38, 20, 0.48)';
export const FLOWER_GARDEN_SPOTLIGHT_RING_COLOR = '#e97b8a';
export const FLOWER_GARDEN_GUIDE_LINE_COLOR = 'rgba(233,123,138,0.7)';
export const FLOWER_GARDEN_ROAMER_SPOTLIGHT_SCALE = 1.0;
export const FLOWER_GARDEN_SPRITE_SPOTLIGHT_SCALE = 1.0;
