import type { RoamerConfig } from '../../core/roamerConfig';

export const BUMBLEBEE_WING_PAIR_COUNT = 1;
export const BUMBLEBEE_LEG_COUNT = 6;
export const BUMBLEBEE_SITTING_FLOWER_COUNT = 12;

export const BUMBLEBEE_WING_PAIR_PICK_BIAS = 1;
export const BUMBLEBEE_SIT_TRANSITION_MS = 300;
export const BUMBLEBEE_SIT_MOVE_RADIUS = 15;
export const BUMBLEBEE_SIT_MOVE_SPEED = 8;
export const BUMBLEBEE_SIT_MOVE_VERTICAL_SQUASH = 0.5;
export const BUMBLEBEE_SIT_PAUSE_DURATION_MS = 4000;
export const BUMBLEBEE_SIT_MOVE_TURN_SPEED = 0.8;
export const BUMBLEBEE_SIT_BODY_SCALE = 0.8;
export const BUMBLEBEE_SIT_DURATION_MIN_MS = 8000;
export const BUMBLEBEE_SIT_DURATION_MAX_MS = 20000;
export const BUMBLEBEE_WAIT_AT_TAKEN_FLOWER_PATIENCE_MS = 4000;
export const BUMBLEBEE_LIFT_OFF_DURATION_MS = 1200;
export const BUMBLEBEE_FLIGHT_PICK_FLOWER_PROBABILITY = 0.65;
export const BUMBLEBEE_SIT_LEG_FREQUENCY = 3;
export const BUMBLEBEE_LEG_FREQUENCY = 8;
export const BUMBLEBEE_LEG_BEND_AMOUNT = 0.3;
export const BUMBLEBEE_LEG_VISIBILITY_FADE_IN_MS = 400;
export const BUMBLEBEE_LEG_VISIBILITY_FADE_OUT_MS = 400;

export const BUMBLEBEE_LEG_TRIPOD_OFFSETS: readonly number[] = [
  0,
  Math.PI,
  Math.PI,
  0,
  0,
  Math.PI,
];

export const BUMBLEBEE_APPROACH_DISTANCE_THRESHOLD = 3;
export const BUMBLEBEE_WING_FREQ_MIN = 20;
export const BUMBLEBEE_WING_FREQ_MAX = 30;
export const BUMBLEBEE_SIT_WING_FREQ_MIN = 1;
export const BUMBLEBEE_SIT_WING_FREQ_MAX = 3;
export const BUMBLEBEE_APPROACH_ORBIT_DURATION_MIN = 4.0;
export const BUMBLEBEE_APPROACH_ORBIT_DURATION_MAX = 6.0;
export const BUMBLEBEE_SIT_WING_PAUSE_DURATION_MIN_MS = 300;
export const BUMBLEBEE_SIT_WING_PAUSE_DURATION_MAX_MS = 1500;
export const BUMBLEBEE_SIT_WING_PRE_TAKEOFF_DURATION_MS = 2000;

export const BUMBLEBEE_NOISE_AMPLITUDE_MIN = 30;
export const BUMBLEBEE_NOISE_AMPLITUDE_MAX = 70;
export const BUMBLEBEE_NOISE_FREQ_MIN = 5;
export const BUMBLEBEE_NOISE_FREQ_MAX = 8;

export const BUMBLEBEE_DEFAULT_SPEED = 20;
export const BUMBLEBEE_BOUNDARY_MARGIN = 50;
export const BUMBLEBEE_SEPARATION_RADIUS = 70;
export const BUMBLEBEE_SEPARATION_STEER = 5;
export const BUMBLEBEE_BOUNDARY_TURN_OFFSET = 0.5;
export const BUMBLEBEE_SWIM_ZONE_TOP_RATIO = 0.5;
export const BUMBLEBEE_HIT_RADIUS = 30;

export const BUMBLEBEE_BASE_SPEED_MIN = 50;
export const BUMBLEBEE_BASE_SPEED_MAX = 60;
export const BUMBLEBEE_CRUISE_DURATION_MIN = 0.8;
export const BUMBLEBEE_CRUISE_DURATION_MAX = 3.0;
export const BUMBLEBEE_CRUISE_DURATION_JITTER = 1.0;

export const BUMBLEBEE_IDLE_DURATION_BASE = 1.5;
export const BUMBLEBEE_IDLE_DURATION_JITTER = 0.6;

export const BUMBLEBEE_ANGLE_LERP = 2.0;
export const BUMBLEBEE_WANDER_LERP = 0.8;
export const BUMBLEBEE_SPEED_LERP_FACTOR = 3.5;

export const BUMBLEBEE_BOUNDARY_MARGIN_RATIO = 0.18;

export const BUMBLEBEE_WANDER_DEVIATION_MIN = -Math.PI;
export const BUMBLEBEE_WANDER_DEVIATION_MAX = Math.PI;

export const BUMBLEBEE_IDLE_NOISE_AMPLITUDE = 30;
export const BUMBLEBEE_IDLE_NOISE_FREQUENCY = 6;

export const BUMBLEBEE_IDLE_DRIFT_SPEED = 3;
export const BUMBLEBEE_SIM_FPS = 30;
export const BUMBLEBEE_SIM_STEP_MS = 1000 / BUMBLEBEE_SIM_FPS;

export const BUMBLEBEE_LAND_AMPLITUDE_BOOST = 17;
export const BUMBLEBEE_TAKEOFF_AMPLITUDE_BOOST = 14;
export const BUMBLEBEE_FLOWER_SWING_BOOST_DECAY_RATE = 2.0;

export const bumblebeeRoamerConfig: RoamerConfig = {
  boundaryMargin: BUMBLEBEE_BOUNDARY_MARGIN,
  baseSpeedMin: BUMBLEBEE_BASE_SPEED_MIN,
  baseSpeedMax: BUMBLEBEE_BASE_SPEED_MAX,
  cruiseDurationMin: BUMBLEBEE_CRUISE_DURATION_MIN,
  cruiseDurationMax: BUMBLEBEE_CRUISE_DURATION_MAX,
  cruiseDurationJitter: BUMBLEBEE_CRUISE_DURATION_JITTER,
  idleDurationBase: BUMBLEBEE_IDLE_DURATION_BASE,
  idleDurationJitter: BUMBLEBEE_IDLE_DURATION_JITTER,
  angleLerp: BUMBLEBEE_ANGLE_LERP,
  wanderLerp: BUMBLEBEE_WANDER_LERP,
  speedLerpFactor: BUMBLEBEE_SPEED_LERP_FACTOR,

  noiseAmplitudeMin: BUMBLEBEE_NOISE_AMPLITUDE_MIN,
  noiseAmplitudeMax: BUMBLEBEE_NOISE_AMPLITUDE_MAX,
  noiseFreqMin: BUMBLEBEE_NOISE_FREQ_MIN,
  noiseFreqMax: BUMBLEBEE_NOISE_FREQ_MAX,
  idleNoiseAmplitude: BUMBLEBEE_IDLE_NOISE_AMPLITUDE,
  idleNoiseFrequency: BUMBLEBEE_IDLE_NOISE_FREQUENCY,
  idleDriftSpeed: BUMBLEBEE_IDLE_DRIFT_SPEED,

  boundaryTurnOffset: BUMBLEBEE_BOUNDARY_TURN_OFFSET,
  boundaryMarginRatio: BUMBLEBEE_BOUNDARY_MARGIN_RATIO,
  separationRadius: BUMBLEBEE_SEPARATION_RADIUS,
  separationSteer: BUMBLEBEE_SEPARATION_STEER,

  wingFreqMin: BUMBLEBEE_WING_FREQ_MIN,
  wingFreqMax: BUMBLEBEE_WING_FREQ_MAX,

  approachDistanceThreshold: BUMBLEBEE_APPROACH_DISTANCE_THRESHOLD,
  approachOrbitDurationMin: BUMBLEBEE_APPROACH_ORBIT_DURATION_MIN,
  approachOrbitDurationMax: BUMBLEBEE_APPROACH_ORBIT_DURATION_MAX,
  flightPickFlowerProbability: BUMBLEBEE_FLIGHT_PICK_FLOWER_PROBABILITY,
  sitTransitionMs: BUMBLEBEE_SIT_TRANSITION_MS,
  sitMoveRadius: BUMBLEBEE_SIT_MOVE_RADIUS,
  sitMoveSpeed: BUMBLEBEE_SIT_MOVE_SPEED,
  sitMoveVerticalSquash: BUMBLEBEE_SIT_MOVE_VERTICAL_SQUASH,
  sitPauseDurationMs: BUMBLEBEE_SIT_PAUSE_DURATION_MS,
  sitMoveTurnSpeed: BUMBLEBEE_SIT_MOVE_TURN_SPEED,
  sitBodyScale: BUMBLEBEE_SIT_BODY_SCALE,
  sitDurationMinMs: BUMBLEBEE_SIT_DURATION_MIN_MS,
  sitDurationMaxMs: BUMBLEBEE_SIT_DURATION_MAX_MS,
  waitAtTakenFlowerPatienceMs: BUMBLEBEE_WAIT_AT_TAKEN_FLOWER_PATIENCE_MS,
  liftOffDurationMs: BUMBLEBEE_LIFT_OFF_DURATION_MS,
  sitWingFreqMin: BUMBLEBEE_SIT_WING_FREQ_MIN,
  sitWingFreqMax: BUMBLEBEE_SIT_WING_FREQ_MAX,
  sitWingPauseDurationMinMs: BUMBLEBEE_SIT_WING_PAUSE_DURATION_MIN_MS,
  sitWingPauseDurationMaxMs: BUMBLEBEE_SIT_WING_PAUSE_DURATION_MAX_MS,
  sitWingPreTakeoffDurationMs: BUMBLEBEE_SIT_WING_PRE_TAKEOFF_DURATION_MS,

  landAmplitudeBoost: BUMBLEBEE_LAND_AMPLITUDE_BOOST,
  takeoffAmplitudeBoost: BUMBLEBEE_TAKEOFF_AMPLITUDE_BOOST,
  flowerSwingBoostDecayRate: BUMBLEBEE_FLOWER_SWING_BOOST_DECAY_RATE,

  legFrequency: BUMBLEBEE_LEG_FREQUENCY,
  legBendAmount: BUMBLEBEE_LEG_BEND_AMOUNT,
  legVisibilityFadeInMs: BUMBLEBEE_LEG_VISIBILITY_FADE_IN_MS,
  legVisibilityFadeOutMs: BUMBLEBEE_LEG_VISIBILITY_FADE_OUT_MS,

  simFps: BUMBLEBEE_SIM_FPS,
  simStepMs: BUMBLEBEE_SIM_STEP_MS,
};
