export const BUMBLEBEE_BODY_LENGTH = 35;
export const BUMBLEBEE_BODY_THICKNESS = 35;
export const BUMBLEBEE_BODY_SCALE = 1;

export const BUMBLEBEE_RENDER_BOUNDS_MARGIN = 10;
export const BUMBLEBEE_HIT_RADIUS = 30;

export const BUMBLEBEE_WING_LENGTH = 12;
export const BUMBLEBEE_WING_THICKNESS = 10;
export const BUMBLEBEE_WING_PHASE1_ANGLE = 0.5;
export const BUMBLEBEE_WING_PHASE2_ANGLE = -1.5;
export const BUMBLEBEE_SIT_WING_FOLD_ANGLE = -2.0;
export const BUMBLEBEE_WING_TRANSPARENCY = 0.6;
export const BUMBLEBEE_WING_OVERLAP = 13;
export const BUMBLEBEE_WING_PIVOT_Y = 0;

export const BUMBLEBEE_SHADOW_OFFSET_SITTING_X = 4;
export const BUMBLEBEE_SHADOW_OFFSET_SITTING_Y = 6;
export const BUMBLEBEE_SHADOW_OFFSET_FLYING_X = 12;
export const BUMBLEBEE_SHADOW_OFFSET_FLYING_Y = -55;
export const BUMBLEBEE_SHADOW_SIZE_SITTING = 1.0;
export const BUMBLEBEE_SHADOW_SIZE_FLYING = 1.4;
export const BUMBLEBEE_SHADOW_OPACITY_SITTING = 0.6;
export const BUMBLEBEE_SHADOW_OPACITY_FLYING = 0.3;
